#![allow(non_snake_case)]

use std::ffi::c_void;

use windows::Win32::{
    Foundation::HWND, System::Threading::RTL_CRITICAL_SECTION, UI::WindowsAndMessaging::HICON,
};

use crate::{
    stub::{ResourceManager, StdBasicString, StdList, StdMap, StdSet},
    Buffer, DDInterface, MusicInterface, Ratio, SoundManager, TRect, WidgetManager,
};

#[repr(C)]
pub struct SexyAppBase {
    unknown0: [u8; 8],
    pub mRandSeed: u32,
    pub mCompanyName: StdBasicString,
    pub mFullCompanyName: StdBasicString,
    pub mProdName: StdBasicString,
    pub mTitle: StdBasicString,
    pub mRegKey: StdBasicString,
    pub mChangeDirTo: StdBasicString,
    pub mRelaxUpdateBacklogCount: i32,
    pub mPreferredX: i32,
    pub mPreferredY: i32,
    pub mWidth: i32,
    pub mHeight: i32,
    pub mFullscreenBits: i32,
    unknown1: [u8; 4],
    pub mMusicVolume: f64,
    pub mSfxVolume: f64,
    pub mDemoMusicVolume: f64,
    pub mDemoSfxVolume: f64,
    pub mNoSoundNeeded: bool,
    pub mWantFMod: bool,
    pub mCmdLineParsed: bool,
    pub mSkipSignatureChecks: bool,
    pub mStandardWordWrap: bool,
    pub mbAllowExtendedChars: bool,
    pub mMutex: *mut c_void,
    pub mOnlyAllowOneCopyToRun: bool,
    pub mNotifyGameMessage: u32,
    pub mCritSect: RTL_CRITICAL_SECTION,
    pub mBetaValidate: bool,
    pub mAdd8BitMaxTable: [u8; 512],
    pub mWidgetManager: *mut WidgetManager,
    pub mDialogMap: StdMap,
    pub mDialogList: StdMap,
    pub mPrimaryThreadId: u32,
    pub mSEHOccured: bool,
    pub mShutdown: bool,
    pub mExitToTop: bool,
    pub mIsWindowed: bool,
    pub mIsPhysWindowed: bool,
    pub mFullScreenWindow: bool,
    pub mForceFullscreen: bool,
    pub mForceWindowed: bool,
    pub mInitialized: bool,
    pub mProcessInTimer: bool,
    pub mTimeLoaded: u32,
    pub mHWnd: *mut HWND,
    pub mInvisHWnd: *mut HWND,
    pub mIsScreenSaver: bool,
    pub mAllowMonitorPowersave: bool,
    pub mDeferredMessages: StdList,
    pub mNoDefer: bool,
    pub mFullScreenPageFlip: bool,
    pub mTabletPC: bool,
    pub mDDInterface: *mut DDInterface,
    pub mAlphaDisabled: bool,
    pub mMusicInterface: *mut MusicInterface,
    pub mReadFromRegistry: bool,
    pub mRegisterLink: StdBasicString,
    pub mProductVersion: StdBasicString,
    pub mCursorImages: [u8; 52],
    pub mOverrideCursor: *mut HICON,
    pub mIsOpeningURL: bool,
    pub mShutdownOnURLOpen: bool,
    pub mOpeningURL: StdBasicString,
    pub mOpeningURLTime: u32,
    pub mLastTimerTime: u32,
    pub mLastBigDelayTime: u32,
    pub mUnmutedMusicVolume: f64,
    pub mUnmutedSfxVolume: f64,
    pub mMuteCount: i32,
    pub mAutoMuteCount: i32,
    pub mDemoMute: bool,
    pub mMuteOnLostFocus: bool,
    pub mMemoryImageSet: StdSet,
    pub mSharedImageMap: StdMap,
    pub mCleanupSharedImages: bool,
    pub mNonDrawCount: i32,
    pub mFrameTime: i32,
    pub mIsDrawing: bool,
    pub mLastDrawWasEmpty: bool,
    pub mHasPendingDraw: bool,
    unknown2: [u8; 5],
    pub mPendingUpdatesAcc: f64,
    pub mUpdateFTimeAcc: f64,
    pub mLastTimeCheck: u32,
    pub mLastTime: u32,
    pub mLastUserInputTick: u32,
    pub mSleepCount: i32,
    pub mDrawCount: i32,
    pub mUpdateCount: i32,
    pub mUpdateAppState: i32,
    pub mUpdateAppDepth: i32,
    pub mUpdateMultiplier: f64,
    pub mPaused: bool,
    pub mFastForwardToUpdateNum: i32,
    pub mFastForwardToMarker: bool,
    pub mFastForwardStep: bool,
    pub mLastDrawTick: u32,
    pub mNextDrawTick: u32,
    pub mStepMode: i32,
    pub mCursorNum: i32,
    pub mSoundManager: *mut SoundManager,
    pub mHandCursor: *mut HICON,
    pub mDraggingCursor: *mut HICON,
    pub mSafeDeleteList: StdList,
    pub mMouseIn: bool,
    pub mRunning: bool,
    pub mActive: bool,
    pub mMinimized: bool,
    pub mPhysMinimized: bool,
    pub mIsDisabled: bool,
    pub mHasFocus: bool,
    pub mDrawTime: i32,
    pub mFPSStartTick: u32,
    pub mFPSFlipCount: i32,
    pub mFPSDirtyCount: i32,
    pub mFPSTime: i32,
    pub mFPSCount: i32,
    pub mShowFPS: bool,
    pub mShowFPSMode: i32,
    pub mScreenBltTime: i32,
    pub mAutoStartLoadingThread: bool,
    pub mLoadingThreadStarted: bool,
    pub mLoadingThreadCompleted: bool,
    pub mLoaded: bool,
    pub mYieldMainThread: bool,
    pub mLoadingFailed: bool,
    pub mCursorThreadRunning: bool,
    pub mSysCursor: bool,
    pub mCustomCursorsEnabled: bool,
    pub mCustomCursorDirty: bool,
    pub mLastShutdownWasGraceful: bool,
    pub mIsWideWindow: bool,
    pub mWriteToSexyCache: bool,
    pub mSexyCacheBuffers: bool,
    pub mNumLoadingThreadTasks: i32,
    pub mCompletedLoadingThreadTasks: i32,
    pub mRecordingDemoBuffer: bool,
    pub mPlayingDemoBuffer: bool,
    pub mManualShutdown: bool,
    pub mDemoPrefix: StdBasicString,
    pub mDemoFileName: StdBasicString,
    pub mDemoBuffer: Buffer,
    pub mDemoLength: i32,
    pub mLastDemoMouseX: i32,
    pub mLastDemoMouseY: i32,
    pub mLastDemoUpdateCnt: i32,
    pub mDemoNeedsCommand: bool,
    pub mDemoIsShortCmd: bool,
    pub mDemoCmdNum: i32,
    pub mDemoCmdOrder: i32,
    pub mDemoCmdBitPos: i32,
    pub mDemoLoadingComplete: bool,
    pub mHandleToIntMap: StdMap,
    pub mCurHandleNum: i32,
    pub mDemoMarkerList: StdList,
    pub mDebugKeysEnabled: bool,
    pub mEnableMaximizeButton: bool,
    pub mCtrlDown: bool,
    pub mAltDown: bool,
    pub mAllowAltEnter: bool,
    pub mSyncRefreshRate: i32,
    pub mVSyncUpdates: bool,
    pub mVSyncBroken: bool,
    pub mVSyncBrokenCount: i32,
    pub mVSyncBrokenTestStartTick: u32,
    pub mVSyncBrokenTestUpdates: u32,
    pub mWaitForVSync: bool,
    pub mSoftVSyncWait: bool,
    pub mUserChanged3DSetting: bool,
    pub mAutoEnable3D: bool,
    pub mTest3D: bool,
    pub mMinVidMemory3D: u32,
    pub mRecommendedVidMemory3D: u32,
    pub mWidescreenAware: bool,
    pub mWidescreenTranslate: bool,
    pub mScreenBounds: TRect<i32>,
    pub mEnableWindowAspect: bool,
    pub mWindowAspect: Ratio,
    pub mStringProperties: StdMap,
    pub mBoolProperties: StdMap,
    pub mIntProperties: StdMap,
    pub mDoubleProperties: StdMap,
    pub mStringVectorProperties: StdMap,
    pub mResourceManager: *mut ResourceManager,
    pub mOldWndProc: i32,
    pub unknown3: [u8; 4],
}
